name: SonarCloud Integration

on:
  push:
    branches:
      - feat-devsecops

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate project existence on SonarCloud
        id: ValidateProjectSonar
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        run: |
          set +e

          # Verificar si el proyecto ya existe en SonarCloud
          response=$(curl -s -f -X GET -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/projects/search?organization=devseco&projects=Laboratorio-final')

          if echo "$response" | grep -q '"name":"Laboratorio-final"'; then
            echo "Project cristinamatheuv/Laboratorio-final already exists on SonarCloud"
          else
            echo "Project cristinamatheuv/Laboratorio-final does not exist on SonarCloud, creating..."

            # Crear el proyecto en SonarCloud
            create_project_response=$(curl -s -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/projects/create' \
              -d "name=Laboratorio-final" \
              -d "organization=devseco" \
              -d "visibility=public")

            if echo "$create_project_response" | grep -q '"errors"'; then
              echo "Failed to create project on SonarCloud"
              exit 1
            fi

            echo "Project cristinamatheuv/Laboratorio-final created successfully on SonarCloud"
          fi

          # Renombrar la rama principal del proyecto si se creó correctamente
          echo "Setting 'main' as the default branch"
          rename_branch_response=$(curl -s -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/project_branches/rename' \
            -d "name=main" \
            -d "project=Laboratorio-final")

          if echo "$rename_branch_response" | grep -q '"errors"'; then
            echo "Failed to rename main branch on SonarCloud"
            exit 1
          fi

          echo "Main branch renamed successfully on SonarCloud"

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        run: sonar-scanner
