name: Workflow

on:
  push:
    branches:
      - feat-devsecops

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validating project existence on SonarCloud
        id: ValidateProjectSonar
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        run: |
          set +e
          curl -f -X GET -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/projects/search?organization=devseco&projects=${{ github.event.repository.name }}' \
            | grep -q '"name":"${{ github.event.repository.name }}"'

          if [ $? -eq 0 ]; then
            echo "Project ${GITHUB_REPOSITORY} already exists on SonarCloud"
          else
            echo "Project ${GITHUB_REPOSITORY} does not exist on SonarCloud, creating..."
            curl -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/projects/create' \
              -d "name=${{ github.event.repository.name }}" \
              -d "projects=${{ github.event.repository.name }}" \
              -d "organization=devseco" \
              -d "visibility=public"
            
            echo "Project ${GITHUB_REPOSITORY} created successfully on SonarCloud"
            
            echo "Setting 'main' as the default branch"
            curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/project_branches/rename' \
              -d "name=main" \
              -d "projects=${{ github.event.repository.name }}"
          fi
