name: Workflow

on:
  push:
    branches:
      - feat-devsecops

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Validate Project on SonarCloud
      #   env:
      #     SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
      #   run: |
      #     set +e
      #     curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' \
      #       -d "name=${{ github.event.repository.name }}" \
      #       -d "project=${{ github.event.repository.name }}" \
      #       -d "organization=devsecops7" \
      #       -d "visibility=public"
      #     if [ $? -ne 0 ]; then
      #       echo "No se puede crear el proyecto en SonarCloud"
      #     else
      #       echo "El Proyecto ${{ github.event.repository.name }} fue creado exitosamente en SonarCloud"
      #       echo "Estableciendo la rama main como rama por defecto"
      #       curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' \
      #         -d "name=main" \
      #         -d "project=${{ github.event.repository.name }}"
      #     fi

      # - name: Run SonarCloud Scan
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     npx sonar-scanner \
      #       -Dsonar.organization=devsecops7 \
      #       -Dsonar.projectKey= ${{ github.event.repository.name }} \
      #       -Dsonar.host.url=https://sonarcloud.io \
      #       -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  #------------SCA-----------------

  SCA:
    needs: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: "${{github.event.repository.name}}"
          path: "."
          format: "HTML"
          out: "report"
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: List report directory for debugging
        run: ls -R /home/runner/work/Laboratorio-final/Laboratorio-final/report

      - name: Upload Test Result
        uses: actions/upload-artifact@v2
        with:
          name: Depcheck Report
          path: /home/runner/work/Laboratorio-final/Laboratorio-final/report
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
