name: Workflow

on:
  push:
    branches:
      - feat-devsecops

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script with a secret
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        run: echo "The secret is $SONAR_TOKEN"
