name: Workflow

on:
  push:
    branches:
      - feat-devsecops

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validating project existence on SonarCloud
        id: ValidateProjectSonar
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        run: |
          set +e

          # Verificar si el proyecto ya existe en SonarCloud
          curl -f -X GET -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/projects/search?organization=devseco&projects=Laboratorio-final' \
            | grep -q '"name":"Laboratorio-final"'

          if [ $? -eq 0 ]; then
            echo "Project cristinamatheuv/Laboratorio-final already exists on SonarCloud"
          else
            echo "Project cristinamatheuv/Laboratorio-final does not exist on SonarCloud, creating..."

            # Crear el proyecto en SonarCloud
            curl -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/projects/create' \
              -d "name=Laboratorio-final" \
              -d "projects=Laboratorio-final" \
              -d "organization=devseco" \
              -d "visibility=public"

            echo "Project cristinamatheuv/Laboratorio-final created successfully on SonarCloud"
          fi

          # Renombrar la rama principal del proyecto si se creó
          if [ $? -eq 0 ]; then
            echo "Setting 'main' as the default branch"
            curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/project_branches/rename' \
              -d "name=main" \
              -d "project=Laboratorio-final"
          fi
